spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mariadb://liquor-business-db.cdi4cweas6u0.ap-northeast-2.rds.amazonaws.com:3306/liquor_business?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: liquorbusinessdb0411
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        show_sql: true
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    open-in-view: false